baseURL: https://www.cabaretbrulee.com
title: Cabaret Brulee
defaultContentLanguage: 'en'
theme: ["hugo-cloak-email", "eternity"]

params:
  logo: cabaret_logo.png
  subtitle: A drag, burlesque and live music show, monthly at CC Bloom's bar, Edinburgh.
  copyright: All rights reserved.
  author: Mariana Vamplew
  dontShowSource: true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://www.instagram.com/cabaretbrulee/'
  homepage: "/home"
  specialPages:
    - home
  bypassWelcomePage: true
  disableRadius: true
  moveIt: false
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  home: ":filename/"

menu:
  main:
    - name: home
      url: /home/
      weight: 1
    - name: tickets
      url: https://www.outsavvy.com/organiser/cabaret-brulee
      weight: 5
